### ISSUE TITLE
Reload command

### ISSUE THREAD

**Issue by astei** [VelocityPowered/Velocity#110]
In essence:

* Reload the `velocity.toml` in-place as much as reasonably (and safely) possible.
* Fire a `ProxyReloadEvent` to allow plugins to reload their own configurations.

**Comment by astei** [comment]
See #139 for most recent work on this.

**Comment by LartyHD** [comment]
Does anyone else work here?

**Comment by astei** [comment]
I work on Velocity in whatever time I have between my contracted work and college.

Anyway, yes, this is fixed. I've been busy with finals and so looking and caring for the issue tracker hasn't been a big priority for me.
