### ISSUE TITLE
DisconnectEvent not called

### ISSUE THREAD

**Issue by BukkitTNT** [VelocityPowered/Velocity#111]
https://github.com/VelocityPowered/Velocity/blob/6ed772ba14f92b6f01f89efaa769b7e47a7c6924/proxy/src/main/java/com/velocitypowered/proxy/connection/client/ConnectedPlayer.java#L311

You should call the DisconnectEvent (or something related here) because otherwise it's not possible to catch this result via velocity-api.

**Comment by Miclebrick** [comment]
It says in the comment they're not connected yet, so why a disconnect event? If anything a connection failed event or something?

**Comment by BukkitTNT** [comment]
> It says in the comment they're not connected yet, so why a disconnect event? If anything a connection failed event or something?
I am well aware that the player is not yet connected.

I wrote  "DisconnectEvent (or something related here)"

**Comment by astei** [comment]
I think a better description of this would be "DisconnectEvent is not consistently fired". We already fire this event for the common case of someone disconnecting from the proxy and for most proxy-caused disconnected, but we didn't always fire it consistently for some proxy-caused disconnects. Those issues are fixed now - `DisconnectEvent` is now _always_ fired when a `ConnectedPlayer` object exists.
