### ISSUE TITLE
Basic permission setting support

### ISSUE THREAD

**Issue by astei** [VelocityPowered/Velocity#118]
Some people genuinely do not need a large, complex permissions plugin such as LuckPerms. Some people may prefer a very basic permissions configuration integrated into Velocity.

This system would by no means replace more complex permissions plugins, only provide a basic floor of support.

**Comment by LartyHD** [comment]
Hm, what features should such a system, in my opinion, please have?

**Comment by NEXUS2345** [comment]
I personally support the idea of using a LuckPerms style system. It is very flexible and allows for a wide breadth of configurations.

**Comment by astei** [comment]
This is better left to a minimal plugin
