### ISSUE TITLE
Plans on SQL drivers

### ISSUE THREAD

**Issue by Rsl1122** [VelocityPowered/Velocity#127]
Hello!

I was just wondering what kind of direction will you be taking with SQL Drivers - Will you be taking the [Sponge route](https://docs.spongepowered.org/stable/en/plugin/database.html) and provide a DataSource, Bungee route of including a driver in the library, or having all plugins shade in their own database drivers?

Sorry if this is the wrong place for this discussion.

Thanks!
Rsl

**Comment by astei** [comment]
Velocity is unlikely to introduce any database abstractions or JDBC drivers into core.

My reason for this is pragmatic as it is simple: we don't want to choose databases to promote. Everyone has different needs and Velocity can't possibly meet them all.

What if, say, Velocity included PostgreSQL drivers but you use MySQL? How about Velocity including MySQL drivers when you really use `$nosql_db_of_the_week`?

**Comment by astei** [comment]
There is a small possibility that with commmunity direction we might include some of these but I don't view it as likely.
