### ISSUE TITLE
Expose ProtocolConstants to the API

### ISSUE THREAD

**Issue by Crypnotic** [VelocityPowered/Velocity#134]
One of the downfalls of Bungeecord and Spigot(along with their forks, afaik) is that there is no API to determine a player's client version. I'm working to fix this issue for Velocity so that developers can cater functions based on a player's version with ease.

Tracking Branch: 
https://github.com/Crypnotic/Velocity/tree/protocol-constants-rework

**Comment by dualspiral** [comment]
Could you make this a PR so it's easier to have discussions about specific things you've done?

**Comment by MiniDigger** [comment]
>  Spigot(along with their forks, afaik) 

kinda offtopic, but paper exposes this:
https://github.com/PaperMC/Paper/blob/1e39773b5340e39aa49cafae057409bd28cdea22/Spigot-API-Patches/0069-Expose-client-protocol-version-and-virtual-host.patch
https://github.com/PaperMC/Paper/blob/459987d69fc6be722321dfbf42547613a62daaed/Spigot-Server-Patches/0209-Expose-client-protocol-version-and-virtual-host.patch

**Comment by astei** [comment]
Velocity exposes this already. Every `Player` is also an `InboundConnection`, which contains the virtual host and protocol version.

**Comment by Crypnotic** [comment]
The purpose was to give developers a nice way to deal with a player's protocol versions without having to know/map every version themselves

**Comment by astei** [comment]
With #135 merged, this is now implemented.
