### ISSUE TITLE
exception when connecting to proxy

### ISSUE THREAD

**Issue by BukkitTNT** [VelocityPowered/Velocity#150]
Velocity throws an exception while connecting to paperspigot 1.13.2 server via "modern" mode.

Exception: https://gist.github.com/BukkitTNT/66016fe445e9f2a96753cafc574c8bdc

Paperspigot isn't recognising a new connection.
Occured after reconnecting the proxy.

**Comment by astei** [comment]
Did you enable the Velocity forwarding support in `paper.yml`?

**Comment by BukkitTNT** [comment]
Yes

**Comment by astei** [comment]
Paste your `velocity.toml`, your `paper.yml`, your `spigot.yml`, and any logs you have.

**Comment by BukkitTNT** [comment]
https://gist.github.com/BukkitTNT/20c51dcd0880488bd739f851debafd25

**Comment by astei** [comment]
I am unable to reproduce this issue, using the latest version of Velocity from master (edfdcf3) and the latest build of Paper (at this time, the latest 1.13.x version is build 463).

**Comment by hugmanrique** [comment]
You have `bungeecord` set to `false` in your `spigot.yml` config. I believe it should be set to true (https://docs.velocitypowered.com/en/latest/users/player-info-forwarding.html#spigot-paper )

**Comment by astei** [comment]
@hugmanrique Nope, that's for legacy forwarding. They want to use modern forwarding.
