### ISSUE TITLE
Download speed

### ISSUE THREAD

**Issue by LartyHD** [VelocityPowered/Velocity#151]
https://www.velocitypowered.com/downloads has a download limit from ~66KB/s, that is very slow.
Pls fix that

**Comment by DoNotSpamPls** [comment]
I can't see what you're talking about, I'm downloading everything in about 3 seconds 😛

**Comment by LartyHD** [comment]
Hm 
> I can't see what you're talking about, I'm downloading everything in about 3 seconds 😛

**Comment by lucko** [comment]
> I can't see what you're talking about, I'm downloading everything in about 3 seconds 😛

Likewise, downloads are instant. Perhaps it's a routing issue? :p

**Comment by astei** [comment]
There's not a lot I can do. The server is in the central USA (Iowa), but performance should be fine even from Europe.

Going to close this. This is probably an issue in your end.

**Comment by LartyHD** [comment]
I have tested on my local network (FR / Strasbourg) and on my Server in Frankfurt with a 1GB/s connection to the DENIC

**Comment by astei** [comment]
```
Andrews-iMac:~ andrew$ wget -O /dev/null https://ci.velocitypowered.com/job/velocity/job/master/384/artifact/proxy/build/libs/velocity-proxy-1.0-SNAPSHOT-all.jar
--2018-11-29 16:46:11--  https://ci.velocitypowered.com/job/velocity/job/master/384/artifact/proxy/build/libs/velocity-proxy-1.0-SNAPSHOT-all.jar
Resolving ci.velocitypowered.com (ci.velocitypowered.com)... 104.27.165.151, 104.27.164.151
Connecting to ci.velocitypowered.com (ci.velocitypowered.com)|104.27.165.151|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 12537560 (12M) [application/java-archive]
Saving to: ‘/dev/null’

/dev/null           100%[===================>]  11.96M  12.9MB/s    in 0.9s    

2018-11-29 16:46:13 (12.9 MB/s) - ‘/dev/null’ saved [12537560/12537560]
```

Speed is perfectly fine for me.

**Comment by Leymooo** [comment]
7MB/s from Estonia

**Comment by LartyHD** [comment]
`wget -O /dev/null https://ci.velocitypowered.com/job/velocity/job/master/384/artifact/proxy/build/libs/velocity-proxy-1.0-SNAPSHOT-all.jar
--2018-11-29 22:48:31--  https://ci.velocitypowered.com/job/velocity/job/master/384/artifact/proxy/build/libs/velocity-proxy-1.0-SNAPSHOT-all.jar
Resolving ci.velocitypowered.com (ci.velocitypowered.com)... 104.27.165.151, 104.27.164.151, 2606:4700:30::681b:a497, ...
Connecting to ci.velocitypowered.com (ci.velocitypowered.com)|104.27.165.151|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 12537560 (12M) [application/java-archive]
Saving to: ‘/dev/null’

/dev/null                                                   100%[==========================================================================================================================================>]  11.96M  9.93MB/s   in 1.2s

2018-11-29 22:48:32 (9.93 MB/s) - ‘/dev/null’ saved [12537560/12537560]`

Now is it ok :D. It was probably a temporary problem
