### ISSUE TITLE
Tab Completion Question (probably a Bug)

### ISSUE THREAD

**Issue by LartyHD** [VelocityPowered/Velocity#154]
Is it wanted like that?
![unbenannt](https://user-images.githubusercontent.com/23587853/49321134-f3e03980-f505-11e8-8897-486d8da8174d.PNG)

**Comment by astei** [comment]
I believe you've found a bug. I am working on a fix.

**Comment by LartyHD** [comment]
I am a Beta-Tester (See #147) :D

**Comment by LartyHD** [comment]
merci @astei

**Comment by astei** [comment]
Technically, everyone using Velocity is an alpha tester.
