### ISSUE TITLE
InterruptedIOException after running command?

### ISSUE THREAD

**Issue by Crypnotic** [VelocityPowered/Velocity#168]
I typed `alex ma` in the console meaning to be the web browser. Tab away and do my search. Come back to the console to shutdown since I'm done testing. Press enter to remove the `alex ma` from the command line, but it throws a `InterruptedIOException: Command interrupted`.

Log: https://pastebin.com/ccGm3rFr

**Comment by astei** [comment]
I don't think this is an issue we can fix. It seems like it might be in TerminalConsoleAppender or JLine but I'm not sure.

**Comment by electronicboy** [comment]
https://github.com/jline/jline3/blob/master/terminal/src/main/java/org/jline/utils/ExecHelper.java#L27
Q would mostly be around how are you running the software? e.g. terminal emulator, any multiplexors (screen, tmux, etc)?
