### ISSUE TITLE
Velocity assumes timed out, disconnected player is still connected to the proxy

### ISSUE THREAD

**Issue by ChipWolf** [VelocityPowered/Velocity#174]
![](https://i.imgur.com/tccyZLQ.png)

**Comment by astei** [comment]
Probably has the same cause as https://github.com/SpigotMC/BungeeCord/issues/1218?

**Comment by Ecconia** [comment]
It sounds exactly like the second case I had, just in my setup it had been a timeout on both servers. (First one, then the other one -> blocked like here).
...Pending - searching for relevant logs...

**Comment by Ecconia** [comment]
![screenshot from 2019-02-21 02-45-39](https://user-images.githubusercontent.com/18501527/53137380-d958b200-3582-11e9-9aa6-9a7137227f59.png)

**Comment by astei** [comment]
Well, it wound up being an entirely different issue. The worst part is that it evaded detection for months.

Give the latest Velocity build (number 70) a try.
