### ISSUE TITLE
Connected Player - Server is still starting spam

### ISSUE THREAD

**Issue by ukdyl94** [VelocityPowered/Velocity#175]
When users are quick to press the join on direct connects and in lobby; it causes console spam that usually ends in a crash for the proxy. This has happened on every build that we've tried. We're currently on build 71.

`
> [11:06:00 ERROR]: [connected player] <username> (/<ip address>): disconnected while connecting to atm3: Server is still starting! Please wait before reconnecting.
> [11:06:00 INFO]: [server connection] <username> -> atm3 has disconnected
> [11:06:00 INFO]: [server connection] <username> -> atm3 has connected
> [11:06:00 ERROR]: [connected player] <username> (/<ip address>): disconnected while connecting to atm3: Server is still starting! Please wait before reconnecting.
> [11:06:00 INFO]: [server connection] <username> -> atm3 has disconnected
> [11:06:00 INFO]: [server connection] <username> -> atm3 has connected
> [11:06:00 ERROR]: [connected player] <username> (/<ip address>): disconnected while connecting to atm3: Server is still starting! Please wait before reconnecting.
> [11:06:00 INFO]: [server connection] <username> -> atm3 has disconnected
> [11:06:00 INFO]: [server connection] <username> -> atm3 has connected
> [11:06:00 ERROR]: [connected player] <username> (/<ip address>): disconnected while connecting to atm3: Server is still starting! Please wait before reconnecting.
> [11:06:00 INFO]: [server connection] <username> -> atm3 has disconnected
> [11:06:00 INFO]: [server connection] <username> -> atm3 has connected`

**Comment by astei** [comment]
This is the same issue as #171 - let's talk there.
