### ISSUE TITLE
Not all players' disconnect events are fired on shutdown

### ISSUE THREAD

**Issue by Willsr71** [VelocityPowered/Velocity#178]
It's possible for some players disconnect events to not fire before the connection manager is closed, meaning that there can be hanging players in plugins on shutdown

**Comment by Gabik21MC** [comment]
```
      for (ConnectedPlayer player : ImmutableList.copyOf(connectionsByUuid.values())) {
        player.disconnect(TextComponent.of("Proxy shutting down."));
      }

      this.cm.shutdown();
```
According to my understanding the connection manager has to be closed beforehand.
Also `ConnectedPlayer#disconnect` is not blocking, meaning that the eventManager could shut down before the Event passed.

**Comment by astei** [comment]
This should now be fixed. This will also get backported to 1.0.2.
