### ISSUE TITLE
Incompatibility with some mods' network channels

### ISSUE THREAD

**Issue by Aang23** [VelocityPowered/Velocity#185]
Some mods which uses their own network channel sometimes simply don't work with Velocity (does not happen without the proxy).
I tried removing SpongeForge too, nothing changed.
On my side I created a very simple mod sending packets to the client through a network channel, sometimes I had similar issues.
Some mods which heavily depends on them can prevent the player from even login on onto the server, here's an example with theoneprobe : 
https://gist.github.com/Aang23/d3a314b00baf6981938767bc2b51f0a9

Velocity : https://github.com/VelocityPowered/Velocity/commit/564cb998610b0b5051785524f488ee8344d163d4

May be related to https://github.com/VelocityPowered/Velocity/issues/183

**Comment by astei** [comment]
Old versions of TheOneProbe do not work with Velocity. The latest versions are supposed to work, but I haven't tested this.

The incompatibility boils down, essentially, to a race condition. It appears to be a mod issue that Velocity can not do much about.

I have a branch where I am reworking Velocity's server switching logic which should improve compatibility in the future but I've had other work to do. In addition I will be in Florida for the next three days and won't be able to work on Velocity at all (my laptop is just barely able to run IDEA and Minecraft, let alone a Forge server).

**Comment by astei** [comment]
Recent changes to server transition and plugin message handling should render this issue fixed. I haven't experience any issues, but I haven't tested TheOneProbe yet.
