### ISSUE TITLE
intent like bungeecord

### ISSUE THREAD

**Issue by hp888pl** [VelocityPowered/Velocity#187]
HELLO I'M FROM POLADN (sory for my bad english) velocity has alternative for intent like this https://github.com/SpigotMC/BungeeCord/blob/master/api/src/main/java/net/md_5/bungee/api/event/AsyncEvent.java ?

**Comment by astei** [comment]
No, but Velocity events run in their own thread pool, negating the need for kludges like `AsyncEvent` which are racy in nature.

**Comment by hp888pl** [comment]
Thank you for the quick reply. I must send request to mojang and when proxy wait for response the player are already connected to server. Have you any idea for this?
