### ISSUE TITLE
Possible Velocity Freeze Bug

### ISSUE THREAD

**Issue by Karagra** [VelocityPowered/Velocity#194]
I am using Spigot 1.14 (Not sure if its 1.14 or Velocity)
Velocity build 102
 Your connection has encountered an error. Try again later.
[23:51:32 ERROR]: [connected player] Karagra (/73.100.202.91:52434): exception encountered
io.netty.channel.unix.Errors$NativeIoException: syscall:read(..) failed: Connection reset by peer
        at io.netty.channel.unix.FileDescriptor.readAddress(..)(Unknown Source) ~[Velocity.jar:1.0.0-SNAPSHOT (git-dc6613a3-b102)]

**Comment by astei** [comment]
That log indicates that the client did not cleanly close the connection. I need some more details to work with.

**Comment by xxDark** [comment]
This happens when the client quit the game forcibly, without going into main menu; in this case, connection is not closed normally, default behavior

**Comment by astei** [comment]
This issue has been stale without any significant updates, so I am closing this issue. If this happens again please open a new issue.
