### ISSUE TITLE
Permission check

### ISSUE THREAD

**Issue by KlaroYT** [VelocityPowered/Velocity#199]
After the PermissionsSetupEvent, I set the player his PermissionProvider, this also confirms me that the player has rights to certain commands. (The PermissionProvider implemented by the PermissionProvider and PermissionFunction) However, when executing a command, I get a confirmation that the player has no rights on the command. The question is now whether this is due to me, or an error in Velocity is...?

**Comment by astei** [comment]
Without code for the permission function I can't possibly diagnose the issue.

**Comment by KlaroYT** [comment]
Sorry for my late response.

My PermissionProvider implementation: https://paste.reformcloud.systems/gOoCl4bR3b
My PermissionsSetupListener: https://paste.reformcloud.systems/kNbl6K2sex
My PermissionCheck in the command: https://paste.reformcloud.systems/R601IITotR

There are some debugs in the code, if you need the output contact me please. Thank you very much helping that fast

**Comment by astei** [comment]
I would probably examine the actual result of `getPermissionValue()`. Note that `Tristate.UNDEFINED.asBoolean()` returns false.

I don't believe an issue exists in Velocity, so I'm closing this issue.

**Comment by KlaroYT** [comment]
The problem is that the direct check with asBoolean returns true as you can see in the debug in my permission provider...

**Comment by astei** [comment]
I have already tried a minimal testcase and I haven't reproduced this issue for myself. Something is wrong with your code. All Velocity has in this situation is storing your `PermissionFunction` for the `Player` and posting an event to allow the `PermissionProvider` to be set for a given `PermissionSubject`.

There is very little that can go wrong here. There's only about 70 lines of code that handle permissions directly in all of Velocity.
