### ISSUE TITLE
Trailing colors not applied after TextComponent append

### ISSUE THREAD

**Issue by Crypnotic** [VelocityPowered/Velocity#200]
I've got a TextComponent defined as a prefix which is applied to all messages. At the end of the prefix, there is a color code to be applied. Prefix: `&7[&bPrefix&7] &a`

The messages are then loaded as TextComponent objects.

Once ready to send, I append the message TextComponent to the prefix TextComponent.

The expected behavior is that the entirety of the message, until another code is found, should be green since the prefix has a trailing `&a` color code; however, the message appears white until another color code is found.

Example: http://prntscr.com/nkpxhj

I know this is most likely a kyori issue, but I would rather it be known here

**Comment by hugmanrique** [comment]
First off, appending one TextComponent to another resets all formatting and colors. It's intended behavior.

And yeah, this issue should be moved to kyori's text repo.

**Comment by astei** [comment]
This is not a Velocity issue.
