### ISSUE TITLE
 AntiWDL Not working with Velocity

### ISSUE THREAD

**Issue by bbtiger** [VelocityPowered/Velocity#203]
Not detected AntiWDL And Waterfall can.

**Comment by astei** [comment]
This issue, as described, is incredibly vague. I need more information.

**Comment by astei** [comment]
I may have a theory as to why this is the case. I'll look into this more later.

**Comment by bbtiger** [comment]
When can I fix it?

**Comment by bbtiger** [comment]
velocity-proxy-1.0.0-SNAPSHOT-all#108  Still not supported.

**Comment by astei** [comment]
This issue will be fixed when #204 is merged.

**Comment by bbtiger** [comment]
AntiWDL still does not support velocity

velocity-proxy-1.0.0-SNAPSHOT-all#111.jar
bungeequack-1.0-SNAPSHOT.jar

**Comment by DoNotSpamPls** [comment]
@bbtiger The PR that fixes the issue hasn't been merged yet, please be patient.
