### ISSUE TITLE
Also push the velocity itself to maven

### ISSUE THREAD

**Issue by james58899** [VelocityPowered/Velocity#209]
Also push the velocity itself to maven (not only api)

Useful when you need to access the velocity internal class.
I know this is not safe, but it will be needed in some edge case.

**Comment by astei** [comment]
It's not going to happen. Doing so means that the Velocity implementation becomes API and it becomes much harder to evolve separately from the API.

If you want to shoot yourself in the foot and depend on internal implementation details, then you can have Velocity in your own repository or use reflection. Just don't complain to us when we change xomething and your code breaks.
