### ISSUE TITLE
Velocity should be more defensive against bad plugins

### ISSUE THREAD

**Issue by astei** [VelocityPowered/Velocity#211]
Some of this can be done in the 1.0.0 timeframe, but others will need to wait for Velocity 2.0.0. This is a "tracking issue" of sorts.

## Thrown `Error`s can close player connections or shut down the console thread

This one would violate the usual recommendations of _Effective Java_ and the like, but I place a higher priority on the proxy surviving shutdown than following good coding practices in this case, especially because others don't follow good coding practices or put ancient plugins on a modern proxy.

**Comment by hugmanrique** [comment]
This is a thing I noticed on Discord. Multiple people attempt to initialize stuff on the plugin's constructor. Velocity throws an error, but I don't think it's clear enough considering so many people had trouble with this.

Inserting an additional help message such as `Invalid plugin. Perhaps you attempted to use Velocity's API on your plugin's constructor?` and add a link redirecting to the wiki/JD where people are adviced to move their code to the ProxyInitializeEvent

**Comment by TheCoolOne123** [comment]
I'll be trying to make a new wiki for developers, because 

https://docs.velocitypowered.com/en/latest/developers/creating-your-first-plugin.html

Is causing some confusion that get's these errors

**Comment by md678685** [comment]
@TheCoolOne123 Why not contribute new pages to the [existing docs](https://github.com/VelocityPowered/documentation/)?

**Comment by astei** [comment]
[I've documented the very common error of trying to register things during construction time.](https://docs.velocitypowered.com/en/latest/developers/creating-your-first-plugin.html#a-word-of-caution)

**Comment by mikroskeem** [comment]
>Thrown Errors can close player connections

Yes, for example plugin throwing NoSuchMethodError in its command handler causes connection to be dropped. Wrapping it into try/catch fixes it and is easy enough for pretty much anyone to PR.

**Comment by MeFisto94** [comment]
> Yes, for example plugin throwing NoSuchMethodError in its command handler causes connection to be dropped. Wrapping it into try/catch fixes it and is easy enough for pretty much anyone to PR.

The question for that would be how to react to that, though: Using the already existing logging, add a more "aggresive" warning, disabling the plugin?

**Comment by astei** [comment]
Fixed with c2db8d4
