### ISSUE TITLE
Query support

### ISSUE THREAD

**Issue by LartyHD** [VelocityPowered/Velocity#218]
Can you add this?

https://dinnerbone.com/blog/2011/10/14/minecraft-19-has-rcon-and-query/
https://wiki.vg/Query

**Comment by hugmanrique** [comment]
xPaw, a known developer for coding SteamDB and game-query related stuff, [mentioned](https://dinnerbone.com/blog/2011/10/14/minecraft-19-has-rcon-and-query/#comment-214-by-xpaw) on that same dinnerbone.com post that the rcon protocol is just GSv3.

Velocity already supports the GameSpy Query Protocol v4, but I can't find the changes between each version.

**Comment by astei** [comment]
Query support is already available in Velocity.
