### ISSUE TITLE
Do you understand that?

### ISSUE THREAD

**Issue by LartyHD** [VelocityPowered/Velocity#220]
http://prntscr.com/o53dwr

Code:
```kotlin
 @Subscribe
    fun on(event: ProxyInitializeEvent) {
        Class.forName("SimpleEventBus")
        Class.forName("ClassJavaModuleManager")
        ....
    }
```

i use Velocity 1.0.0 release

**Comment by astei** [comment]
Wrong place to ask. Go look up the Javadocs for `java.lang.Class`.

**Comment by astei** [comment]
Why are you even doing this?!?

**Comment by LartyHD** [comment]
I can't use my API (in a other velocity Plugin)

**Comment by LartyHD** [comment]
And i only use Class.fromName for debuging

**Comment by LartyHD** [comment]
> Wrong place to ask. Go look up the Javadocs for java.lang.Class.

have u seen the screenshot?

**Comment by astei** [comment]
https://docs.oracle.com/javase/8/docs/api/java/lang/Class.html#forName-java.lang.String-

> `className` - the **fully qualified name** of the desired class.

`SimpleEventBus` isn't a fully-qualified name.

**Comment by LartyHD** [comment]
oh good, I almost thought, but just did not write ....
Thx for let me know

**Comment by NycuRO** [comment]
If you use LuckPerms, yes, is it.
