### ISSUE TITLE
Allow BungeeCord-style kick behavior

### ISSUE THREAD

**Issue by astei** [VelocityPowered/Velocity#226]
Velocity currently applies offline-mode style handling for duplicate player logins: it refuses to kick the existing connected player.

BungeeCord allows online-mode servers to replace the existing connection with the new connection. Velocity should add support for this behavior.

**Comment by md678685** [comment]
Should this be exposed through the API or the config (or both)?

**Comment by Aang23** [comment]
At least the config I would say, and maybe an event in the API.

**Comment by astei** [comment]
It'll be exposed through the configuration.

**Comment by astei** [comment]
I've implemented this. The code is sitting on my laptop. I will push it to another branch and test it there.

**Comment by astei** [comment]
Added in 85e5fb4
