### ISSUE TITLE
1.13 Enhancements to Command System

### ISSUE THREAD

**Issue by astei** [VelocityPowered/Velocity#232]
At the moment, Velocity supports old style commands (prior to 1.13): free-form commands that  could be input at will with tab complete.

1.13 has changed the command system: it is now based on [Brigadier](https://github.com/Mojang/brigadier). Given this, how should Velocity adapt to the 1.13+ commands future? I see a few options:

* We keep the current command system, but allow argument metadata to be attached to commands. The advantage is that plugins can gradually add Brigadier support and we don't have to break backwards compatibility, and Velocity can provide a tab-complete fallback when plugins don't provide their own metadata. However, this may make the API more awkward to use.
* We add a parallel command system (which has full backwards-compatibility with 1.12.2 and lower and has a sensible migration path from the current system), deprecate the existing one, and remove it completely in a major release. This is a very disruptive option to take.

Other options are open to discussion, please comment. **This is not final!**

**Comment by NEXUS2345** [comment]
I personally believe that keeping pace with Mojang's development of JE should be a big objective of Velocity. It is one of the things that has led BungeeCord to become quite bloated in my opinion. I would support the latter of the options, as I don't believe making the API more complex to use is a good thing for sustainability and quality of plugins. I can foresee other platforms such as Sponge potentially moving to use Brigadier in future as well, so migrating properly would make more sense to me.

**Comment by astei** [comment]
It seems unlikely we'll get to this in the Velocity 1.1.0 timeframe. As a stopgap, `PlayerAvailableCommandsEvent` can be used in 1.1.0.

The path forward will likely be #330.

**Comment by astei** [comment]
#330 has been long merged in and the issues largely worked out.
