### ISSUE TITLE
Player with flaky internet connection causes velocity to run out of memory

### ISSUE THREAD

**Issue by bluelightning32** [VelocityPowered/Velocity#241]
I was running velocity build #158 since Jun 28. I only restarted it a couple times. I was using this command line:
```
java -Xmx300M -Xms20M -jar velocity-proxy-1.0.3-SNAPSHOT-all.jar
```

On Aug 8, velocity hung. `top` reported it was using lots of CPU (probably continually garbage collecting):
```
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
 2901 minecra+  20   0 9814792 981.8m   8296 S  1133   1.5   1561:13 java
```

I upgraded to build #169, increased the max memory to 400M, and started capturing netstat and top data in the background.

It hung again at 8:34 this morning.
```
top - 08:34:19 up 81 days,  9:10,  2 users,  load average: 10.32, 7.48, 6.01
Tasks:   1 total,   0 running,   1 sleeping,   0 stopped,   0 zombie
%Cpu(s): 54.5 us,  2.7 sy,  0.0 ni, 33.2 id,  8.3 wa,  0.3 hi,  1.0 si,  0.0 st
MiB Mem :  64280.9 total,    421.9 free,  49614.1 used,  14244.8 buff/cache
MiB Swap:  65536.0 total,  64386.2 free,   1149.8 used.  13949.7 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
27159 minecra+  20   0 9168240   1.0g   9800 S 392.0   1.6 622:40.62 java
```

I collected an hprof and sent it to Tux privately. Here is the summary of it from jhat:
![image](https://user-images.githubusercontent.com/21202621/62825380-70301f80-bb5f-11e9-82f4-18c7f8c243f0.png)

I looked back through the top output. The memory usage reported by top will grow every time java grows the heap, but it doesn't go back down unless the process is restarted.

The memory usage slowly rose during this period on Aug 09:
```
top - 08:09:52 up 80 days,  8:46,  5 users,  load average: 2.41, 1.97, 1.67
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
27159 minecra+  20   0 8232248 366760  19852 S  11.0   0.6   0:52.14 java
```
```
top - 08:33:09 up 80 days,  9:09,  5 users,  load average: 5.10, 4.23, 3.54
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
27159 minecra+  20   0 8232248 423428  17184 S  13.0   0.6   3:39.44 java
```

The memory usage rose quickly during this period on Aug 09:
```
top - 08:51:16 up 80 days,  9:27,  5 users,  load average: 3.55, 3.12, 3.08
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
27159 minecra+  20   0 8298812 487516  17664 S  21.0   0.7   6:14.65 java
```
```
top - 08:55:47 up 80 days,  9:32,  5 users,  load average: 3.09, 3.32, 3.18
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
27159 minecra+  20   0 8298812 760676  17668 S  27.0   1.2   7:26.35 java
```

Before then, Coco_Miss's Internet connection was keeping up with the server:
```
tcp6       0      0 192.168.15.2:25568      58.114.231.71:54135     ESTABLISHED 27159/java          
```

Shortly before the incident, her computer could not keep up with what the server was trying to send it:
```
Fri 09 Aug 2019 08:47:01 AM PDT
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp6       0  74880 192.168.15.2:25568      58.114.231.71:54135     ESTABLISHED 27159/java    
```

Her computer continued to be unable to keep up through this point, at which point the velocity server couldn't keep up with what her computer was sending:
```
Fri 09 Aug 2019 08:57:16 AM PDT
tcp6    3890  21600 192.168.15.2:25568      58.114.231.71:54135     ESTABLISHED 27159/java   
```

Velocity couldn't receive data from her computer, because it was continually doing GC:
```
top - 08:57:15 up 80 days,  9:33,  5 users,  load average: 5.98, 3.96, 3.40
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
27159 minecra+  20   0 8498504 784784  17668 S  1180   1.2  11:38.25 java
```

Shortly afterwards Coco_Miss was kicked from the server because the server ran out of memory:
```
[08:57:56] [Netty epoll Worker #2/INFO]: [connected player] Coco_Miss (/58.114.231.71:54135) has disconnected: Your connection has encountered an error. Try again later.
[08:58:04] [Netty epoll Worker #2/ERROR]: [connected player] Coco_Miss (/58.114.231.71:54135): exception encountered
java.lang.OutOfMemoryError: GC overhead limit exceeded
```

The server recovered.
```
top - 08:59:21 up 80 days,  9:35,  5 users,  load average: 14.33, 8.36, 5.12
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
27159 minecra+  20   0 8964452 761692  17968 S   4.0   1.2  35:49.68 java
```

Coco_Miss reconnected, and shortly afterwards her computer was unable to keep up again:
```
Fri 09 Aug 2019 09:30:33 AM PDT
tcp6       0  95040 192.168.15.2:25568      58.114.231.71:54630     ESTABLISHED 27159/java
```
```
Fri 09 Aug 2019 09:46:41 AM PDT
tcp6   13248  28615 192.168.15.2:25568      58.114.231.71:54630     ESTABLISHED 27159/java      
```

During that period, the velocity CPU usage spiked again:
```
top - 09:46:12 up 80 days, 10:22,  5 users,  load average: 4.16, 3.57, 5.57
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
27159 minecra+  20   0 9164144 857744  11052 S 436.0   1.3 149:39.11 java
```

And the player was disconnected again when velocity ran out of memory:
```
[10:02:51] [Netty epoll Worker #0/ERROR]: [connected player] Coco_Miss (/58.114.231.71:54630): exception encountered
java.lang.OutOfMemoryError: Java heap space
```

**Comment by bluelightning32** [comment]
In the heap dump I collected from the last hang, it shows that player and only that player has a huge ping:
![image](https://user-images.githubusercontent.com/21202621/62826073-3d3f5900-bb6a-11e9-80b4-a68c4ea9a75e.png)
![image](https://user-images.githubusercontent.com/21202621/62826076-48928480-bb6a-11e9-8715-2c53cca4752d.png)

**Comment by bluelightning32** [comment]
The velocity server is in front of 4 instances of the DD&SS modpack, version 5.6a. It contains randompatches-1.12.2-1.17.2.1.jar with these settings:
```
timeouts {
    # The interval at which the server sends the KeepAlive packet.
    # Min: 1
    # Max: 2147483647
    # Default: 15
    I:keepAlivePacketInterval=60

    # The login timeout.
    # Min: 1
    # Max: 2147483647
    # Default: 900
    I:loginTimeout=6000

    # Whether to apply the login timeout.
    # Default: true
    B:patchLoginTimeout=true

    # The read timeout.
    # This is the time it takes for a player to be disconnected after not responding to a KeepAlive packet.
    # This value is automatically rounded up to a product of keepAlivePacketInterval.
    # Min: 1
    # Max: 2147483647
    # Default: 90
    I:readTimeout=6000
}
```

**Comment by astei** [comment]
I still need to investigate this further, but Velocity already implements basic flow control that should've allowed the connection to keep up and not cause issues writing packets. If the client is not able to accept all the packets, Velocity will stop reading from the server temporarily to give the client a chance to receive the packets.

**Comment by astei** [comment]
Closing this issue as it is stale. If this issue is still a problem, let me know and we can take another look at this.
