### ISSUE TITLE
Can't connect to forge server

### ISSUE THREAD

**Issue by Preta-Crowz** [VelocityPowered/Velocity#249]
When I try to connect to forge server and console says
`Can't connect to server main: This server has mods that require FML/Forge to be installed on the client. Contact your server admin for more details.`
I already installed forge and every mods from server. But why it happens?

**Comment by Preta-Crowz** [comment]
Fixed

**Comment by MypowerHD** [comment]
How you got fixed that  @Preta-Crowz?

**Comment by Preta-Crowz** [comment]
@MypowerHD 
When I commented this issue, I tried to use double proxies. I just removed one and it fixed.
