### ISSUE TITLE
Improve server switch times

### ISSUE THREAD

**Issue by astei** [VelocityPowered/Velocity#251]
The existing Velocity switching mechanism is based on the sending `JoinGame` packet. There are many advantages:

* Strong compatibility with all modern versions of Minecraft, along with most mods.
* Requires very little work on the proxy (all you need to do is send the right sequence of packets), which means lower CPU usage.
* It is very simple.

However, there are some issues with the current implementation:

* Sending the `JoinGame` packet cause the client to be extremely "chatty" with the backend server, as it is essentially executing the code used to exchange pleasantries with the server. (It is worse as Velocity is currently sending the `JoinGame` and `Respawn` packets twice.
* Server switch times are slower compared to BungeeCord or even switching dimensions on a regular Minecraft server.

We should improve the existing method and consider adding entity ID rewriting.

**Comment by MrIvanPlays** [comment]
> consider adding entity ID rewriting.

This will make it slower. If you remove the entity rewriting in bungee you'll see a bunch of server switch speed increase. It just makes the proxy do more work and so slow down.

**Comment by astei** [comment]
We're not going to make this a default, only for people interested in fast server switches in exchange for higher CPU usage.

**Comment by MrIvanPlays** [comment]
> fast server switches in exchange for higher CPU usage.

but dude im telling you that entity rewrite is all slow shit. just see my waterfall fork where i completely got rid of it and compare it to bungeecord or even waterfall's server switching speeds. trust me on this don't add entity rewriting. faster switch speeds? sure. but DON'T ADD entity rewriting. DON'T

**Comment by mikroskeem** [comment]
>We're not going to make this a default

ah yes, why bother reading

**Comment by Leymooo** [comment]
I made some tests and got this results :

| Platform | First run | Second run | Third run |
| --- | --- | --- | --- |
| BungeeCord | 367ms | 371ms | 375ms |
| IvanCord | 475ms | 484ms | 482ms |
| Velocity 1.1.0 | 371ms  | 379ms | 362ms |
| Velocity 1.0.4 | 480ms | 483ms | 482ms |
| Waterfall di_en_me_re: false | 367ms | 368ms | 364ms |
| Waterfall di_en_me_re: true | 498ms | 486ms | 484ms |

`di_en_me_re` is option `disable_entity_metadata_rewrite` in waterfall.yml

Every run is average time for 200 switches between servers. 

How i calculate switch time:

1. Store current time when `SPacketPlayerListItem` received ([image](https://i.imgur.com/kjh7n0a.png)).
   * SPacketPlayerListItem with action REMOVE - its a first packet that indicate that server switch was started.
2. Wait until `PlayerPositionAndLook` packet. Calculate the time elapsed between this two packets. ([image](https://i.imgur.com/OdTn9uV.png))
    * PlayerPositionAndLook will close LOADING screen, and player can play on new server

Setup:
  * Server HW: i9-9900k. OC up to 4.7. Ubuntu 18.04. Openjdk 8_222-b10
  * Client HW: i5-2320. Windows 10. Openjdk 8_232-b09. Ping to server is 36ms
  * 2xSpigot 1.12.2 servers with ProtocolSupport + my plugin that sends player to another server on join after 20 ticks.
  * 1.12 client (mcp940)

There is very interesting results. Waterfall with entity rewriting is faster, than without. Velocity 1.0.4 server switch is slower than on BungeeCord, but same on 1.1.0.

**Comment by electronicboy** [comment]
without will basically trigger the client to do a full state reset, likely why it's on par with vel 1.0.4; with entity metadata rewriting will make the proxy work harder however as it's gotta handle all that state itself, e.g. sending the scoreboard removal packets, but for a minimal server, that's going to be irrelevant

**Comment by astei** [comment]
The thing I'm curious to know is why Velocity 1.1.0 is on par with BungeeCord and entity ID-rewriting Waterfall.

**Comment by Leymooo** [comment]
maybe native changes give this improvement?

**Comment by astei** [comment]
I suspect so. I paid a lot of attention to optimizing the Velocity pipeline (which includes the natives), and this shows that my work has paid off there.

I'm assuming you had native compression but Java ciphers - given that, this is still quite impressive, so entity ID rewriting may be a net benefit despite the elevated CPU usage. However, due to the need to write this logic from scratch across seven major Minecraft versions, we will likely only use it for select versions of Minecraft at least initially.

**Comment by Leymooo** [comment]
I think i know why it faster. To handle JoinGame packet, client took ~100-200ms. To handle respawn ~100-160ms. So velocity 1.1.0 sends one respawn instead of two in 1.0.4. Also looks like waterfall also sends 2 respawn packets + 1 login when entity rewrite is disabled. 


I think you can close this issue, because adding entity rewrite does not give anything.

**Comment by astei** [comment]
That's not particularly exciting, but I'd be inclined to agree given that 1.1.0 is just as fast as BungeeCord and Waterfall. Thanks for providing some hard data, I appreciate it.
