### ISSUE TITLE
Don't make users depend on the Sponge repo for API 1.1.0

### ISSUE THREAD

**Issue by astei** [VelocityPowered/Velocity#257]
Right now, Configurate is pulled in from the Sponge repos. This causes an unpleasant surprise for people wanting to use the 1.1.0 API.

**Comment by MrIvanPlays** [comment]
ask sponge people to allow you compile it into the api?

**Comment by astei** [comment]
Licensing isn't the concern. Configurate is [Apache 2.0 licensed](https://github.com/SpongePowered/Configurate/blob/master/LICENSE).

**Comment by zml2008** [comment]
at one point configurate was on maven central -- that could probably happen again with sufficient poking of Sponge people -- dropping into the Sponge discord is likely to be productive :)

**Comment by electronicboy** [comment]
Don't recall maven resolving repos transitively, or at least if it did it was shakey and fussy at best as to if it would pick them up (Also, have to be wary with maven and assuming that deps are available if you build some other project that uses a dependency that has the repo, building your project will work as that dependency has been pulled into your local, but would fail on somebody elses machine where they don't)

Easiest way to resolve this one is to get configurate in central, falling on the assumption that people will have central in their build anyways, or; setup a maven mirror and direct people to use that instead

**Comment by astei** [comment]
I was intending on shadowing the dependencies, but my last attempt only resulted in a `all` classifier that I didn't want. I'll try and give this another shot again, but if not, I'll have to investigate turning `repo.velocitypowered.com` into a "real" Maven repository instead of the barebones thing I've got going now.

**Comment by MrIvanPlays** [comment]
> I was intending on shadowing the dependencies, but my last attempt only resulted in a `all` classifier that I didn't want. I'll try and give this another shot again, but if not, I'll have to investigate turning `repo.velocitypowered.com` into a "real" Maven repository instead of the barebones thing I've got going now.

I don't thin the "barebones thing" is the problem; the api is being fetched normaly with maven (and perhaps is fetched normaly with gradle). Shading configurate will fix this problem and it doesn't require much effort to do. Or what you can also do is fork configurate, change packages, upload to the "barebones thing" and depend on that in the api.

**Comment by electronicboy** [comment]
Shading configuate directly won't fix the problem directly, not without
tryna mask it as a transitive so it's not picked up, which imho would just
be gross, reshipping the lib in the velocity repo, (sonatype supports maven
proxy/caching for remote repos), is basically the recommended and defacto
way to handle these kind of situations

**Comment by astei** [comment]
I guess I'll have to start that homelab pretty soon then...

**Comment by Vankka** [comment]
`https://libraries.minecraft.net` is also required for 1.1.0 now

**Comment by astei** [comment]
It's been a long time waiting, [but we've now fixed this issue](https://forums.velocitypowered.com/t/infrastructure-upgrades-new-maven-repository-a-new-sponsor-and-more/464).
