### ISSUE TITLE
Modern Player Forwarding Support

### ISSUE THREAD

**Issue by Manu5656** [VelocityPowered/Velocity#258]
Ciao, ho seguito ciò che avete scritto nelle vostre guide ma quando provo ad entrare nel server vedo un messaggio che dice "**Can't connect to server lobby: Your server did not send a forwarding request to the proxy. Is it set up correctly?**"

Velocity File: https://imgur.com/RckXD2k

Paper File: https://imgur.com/s3A9MoI

Spigot File: https://imgur.com/Y5j62vv

If in the spigot file I set the second word "bungeecord" to true this message is displayed when I try to enter: "**disconnected while connecting to lobby: If you wish to use IP forwarding, please enable it in your BungeeCord config as well!**"

Could you tell me how to solve and configure this feature well? Thanks.

**Comment by astei** [comment]
Your paper.yml is invalid. This is not a Velocity issue.

**Comment by astei** [comment]
The `velocity-support` config section in `paper.yml` is:

```yaml
settings:
  velocity-support:
    enabled: true
    online-mode: true
    secret: 'secret'
```

The format for your `paper.yml` is not correct. Use this format and it will work. Also, enabling BungeeCord and Velocity forwarding support contradict each other.

**Comment by Manu5656** [comment]
So in the spigot.yml file do I have to change anything and it must remain as it was originally?

**Comment by astei** [comment]
You have to make sure `settings.bungeecord` is set to `false`, and then fix `paper.yml` as I mentioned above.

**Comment by Manu5656** [comment]
I modified the paper file: https://imgur.com/xm2E3xN 

I inserted in the spigot file settings.bungeecord: false
Normally in the spigot.yml file there is already a "bungeecord: false" entry, must both be present?
https://imgur.com/hqukwJe

Currently it does not work yet. When I try to log in I see a message saying: _Can't connect to server lobby: Your server did not send forwarding requests to the proxy. Is it set up correctly?_

**Comment by astei** [comment]
This is still not correct. You created a `settings` section inside a `settings` section. Don't do that.

**Comment by Manu5656** [comment]
Perfect, I fixed it. Now it works, thanks a lot!

**Comment by dikovmaxim** [comment]
There is no paper.yml on paper 1.19.2

**Comment by powercasgamer** [comment]
> There is no paper.yml on paper 1.19.2

Please don't leave a comment on a 4 year old issue. It's now in `config/paper-global.yml`

**Comment by maksimus0x** [comment]
HEEEEELP - disconnected while connecting to auth: Your server did not send a forwarding request to the proxy. Make sure the server is configured for Velocity forwarding.

**Comment by Nacioszeczek** [comment]
@1max1g please use our Discord or forums for support and not the GitHub issues.
