### ISSUE TITLE
Command and Permissions

### ISSUE THREAD

**Issue by Manu5656** [VelocityPowered/Velocity#259]
Hi, where is it possible to find a list of the commands in velocity?
Also, how can you manage permissions for these commands? I noticed that by default you can run the command /server and it's not a very nice thing.. 
I would like to remove the permission to do this command from within the server (and the other commands that are there)

**Comment by Lignium** [comment]
You need to install a permission plugin (for example, LuckPerms) and configure the permissions as you like. More about built-in commands and its permissions: https://docs.velocitypowered.com/en/latest/users/commands.html

**Comment by astei** [comment]
This question has been answered for you on Discord. Closing this issue.
