### ISSUE TITLE
[Question] How do I set permission to a user?

### ISSUE THREAD

**Issue by MrIvanPlays** [VelocityPowered/Velocity#264]
Title says it. 

If there's none I can make a basic permission ~~system~~ setter

**Comment by Draycia** [comment]
Hook into permissions plugins, probably. API doesn't have a spec for setting permissions.

**Comment by mikroskeem** [comment]
Why do you need that when you can simply use a plugin?

**Comment by MrIvanPlays** [comment]
> Why do you need that when you can simply use a plugin?

Why should I use a plugin when this can be built in? I mean, hasPermission is already there, we just need default setter implementation

**Comment by DankRank** [comment]
How permissions are stored/calculated is a detail of a particular permission system. Your best bet is to use a permission plugin's API. Alternatively, you could hook PermissionsSetupEvent and do your own permission management on top of an existing permission system.

**Comment by astei** [comment]
Closing as this question has been answered.
