### ISSUE TITLE
Forge 1.14.4 & 1.15.2 Issues

### ISSUE THREAD

**Issue by Siriuo** [VelocityPowered/Velocity#270]
Velocity Version: 1.1.0 build 68

I am unsure if this is currently supported or if I am completely missing something but I am having some issues getting Velocity working with forge 1.14.4 and 1.15.2. I get the below message. 

`Can't connect to server lobby: Your server did not send a forwarding request to the proxy. Is it set up correctly?`

See below the settings which are set
announce-forge = true
player-info-forwarding-mode = "MODERN"
ping-passthrough = "MODS"

All other settings apart from the below are default

```
[servers]
# Configure your servers here. Each key represents the server's name, and the value
# represents the IP address of the server to connect to.
lobby = "127.0.0.1:25566"

# In what order we should try servers when a player logs in or is kicked from aserver.
try = [
  "lobby"
]

[forced-hosts]
# Configure your forced hosts here.
"lobby.example.com" = [
  "lobby"
]
```

**Comment by astei** [comment]
Velocity does not support Forge 1.14/1.15 at the moment. This is a known issue (see #248). It has not been resolved due to a lack of time/resources.
