### ISSUE TITLE
Modify player name

### ISSUE THREAD

**Issue by mcqwy** [VelocityPowered/Velocity#273]
Hello, in plug-in development
How can I change the player's name?
`event.getPlayer().getGameProfile().withName("123456");`
No effect

**Comment by astei** [comment]
`GameProfile` is immutable (so `withName()` returns a new `GameProfile`). The fix is to use the returned `GameProfile`.

**Comment by astei** [comment]
The username can only get changed in `GameProfileRequestEvent` as well.

**Comment by mcqwy** [comment]
Hello, isn't that right
`@Subscribe
	public void onLoginnnnn(GameProfileRequestEvent event)
	{
		GameProfile game = new GameProfile("3ad34411-b368-35db-8526-757934890fe1",
				"Mon_lh",
				event.getGameProfile().getProperties());
		event.setGameProfile(game);
	}`

**Comment by mcqwy** [comment]
![Uploading 123.png…]()
I'm going to use it in offline mode

**Comment by astei** [comment]
Read the documentation for [GameProfile](https://jd.velocitypowered.com/1.0.0/com/velocitypowered/api/util/GameProfile.html) - you have to provide an undashed UUID to the `GameProfile` constructor if you invoke it that way.

Also, you can only change the `GameProfile` if the connection is in offline mode. This is because it allows you to spoof the connection to the backend which defeats the point of doing Mojang authentication.

**Comment by mcqwy** [comment]
Can't I disconnect directly from `GameProfileRequestEvent`?

**Comment by mcqwy** [comment]
There is no such method as event.getconnection().disconnect()

**Comment by astei** [comment]
What are you trying to do?

**Comment by mcqwy** [comment]
I am doing a login verification plug-in
A name you want to return by logging in to the server
For example: =123456789=
After the client gets the name, I set the player's correct name through the name
If =123456789= does not exist in the database, disconnect the connection

**Comment by mcqwy** [comment]
![123](https://user-images.githubusercontent.com/38318368/73980436-250a9400-496b-11ea-92d9-49e5919e46cd.png)

This is my BungeeCord plug-in code
I'm migrating to Velocity

**Comment by mcqwy** [comment]
Hi!
I have found a way
Judge in gameprofilerequestevent
Returns the correct name if it exists in the database
If not, return====
Then get the name in loginevent
Disconnect if name equals = ====
If it is not = = = the game is allowed
Thank you very much for your help
I like velocity very much
