### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by Healthable** [VelocityPowered/Velocity#278]
If it can support BungeeCord plugins,it will be more popular.
As everyone know now has a large number of BungeeCord plugins and BungeeCord plugins's authors
can not want to support Velocity actively.If it can support BungeeCord plugins it will be very convinient for servers.It is only a suggestion. Thanks for your development!

**Comment by astei** [comment]
For various reasons, we will not be supporting BungeeCord plugins on Velocity. From the fact Velocity is an extremely different platform than BungeeCord to plugins expecting every quirk and implementation detail from BungeeCord to be present, it just won't happen without Velocity effectively becoming a BungeeCord fork (which isn't happening).
