### ISSUE TITLE
Add shutdown method to the API

### ISSUE THREAD

**Issue by TheSilentPro** [VelocityPowered/Velocity#280]
Currently, there is no way to shut down the proxy without executing a command, adding a method 
for this would be really helpful.

**Comment by MrIvanPlays** [comment]
Why do you need to shutdown the proxy at first place?

**Comment by astei** [comment]
I have been a bit skeptical of including a shutdown functionality, but I think it has merit. It should be simple to expose the existing Velocity shutdown functions.

**Comment by MrIvanPlays** [comment]
https://github.com/VelocityPowered/Velocity/commit/3beaeb2df76f726e006bf9e99fda0a624be69ae4
