### ISSUE TITLE
Feature Request: Add "first server to connect to" in PostLoginEvent

### ISSUE THREAD

**Issue by robinbraemer** [VelocityPowered/Velocity#286]
It would be great to be able to modify the server, the player first connects to, in the PostLoginEvent!
In source [this](https://github.com/VelocityPowered/Velocity/blob/45574ce9522abd232f8ec30146d6a2b40a35cfb2/proxy/src/main/java/com/velocitypowered/proxy/connection/client/LoginSessionHandler.java#L283) line would be changed and [this](https://github.com/VelocityPowered/Velocity/blob/45574ce9522abd232f8ec30146d6a2b40a35cfb2/proxy/src/main/java/com/velocitypowered/proxy/connection/client/LoginSessionHandler.java#L247) line would need rethought as now also the plugin can set the server, not only those pre-configured.

**Comment by Leymooo** [comment]
1.0.x does not get any API changes or features. Only bug fixes and updates for new MC versions. But you can use 1.1.0 there is [PlayerChooseInitialServerEvent ](https://github.com/VelocityPowered/Velocity/blob/dev/1.1.0/api/src/main/java/com/velocitypowered/api/event/player/PlayerChooseInitialServerEvent.java)

**Comment by astei** [comment]
Implemented in 1.1.0 already as `PlayerChooseInitialServerEvent`
