### ISSUE TITLE
Permanent download link

### ISSUE THREAD

**Issue by derklaro** [VelocityPowered/Velocity#293]
Is there any permanent download link which is not version-sensetive? Currently I am using the download from [https://ci.velocitypowered.com/job/velocity/lastSuccessfulBuild/artifact/proxy/build/libs/velocity-proxy-1.0.8-SNAPSHOT-all.jar](https://ci.velocitypowered.com/job/velocity/lastSuccessfulBuild/artifact/proxy/build/libs/velocity-proxy-1.0.8-SNAPSHOT-all.jar) but this is version sensetive any fails after the release of a new version 😞

**Comment by astei** [comment]
It's been planned, but has not been high priority due to lack of resources and time. We'll see after I finish this big project I have to work on...

**Comment by FerusGrim** [comment]
Can put this JS anywhere.

```javascript
    const CORS_PROXY = 'https://cors-anywhere.herokuapp.com/'
    const FETCH_JSON_URL = 'https://ci.velocitypowered.com/job/velocity/lastSuccessfulBuild/api/json'
    const RESPONSE_BASE = 'https://ci.velocitypowered.com/job/velocity/lastSuccessfulBuild/artifact/'

    fetch(CORS_PROXY + FETCH_JSON_URL)
        .then(response => response.json())
        .then(data => RESPONSE_BASE + data.artifacts[0].relativePath)
        .then(url => window.location = url)
        .catch(err => console.error(err))
```
I've put up a [working example](https://velocity.ferus.xyz/) that can be used for now, but it really only takes an html file with that script and a server to host it to be pointed at.

**Comment by astei** [comment]
I have written a small Cloudflare worker to handle this:

To get the latest possible version:

https://versions.velocitypowered.com/version/latest
https://versions.velocitypowered.com/download/latest.jar

To get the latest possible version for 1.0.x:

https://versions.velocitypowered.com/version/1.0
https://versions.velocitypowered.com/download/1.0.jar

and so on. I consider this issue resolved now.
