### ISSUE TITLE
Make prevent-proxy-connections optional

### ISSUE THREAD

**Issue by Cybermaxke** [VelocityPowered/Velocity#296]
This refers to the `ip` parameter in the `hasJoined` block, which is optionally used in vanilla mc but isn't in velocity. This should also become an option in velocity.

`https://sessionserver.mojang.com/session/minecraft/hasJoined?username=username&serverId=hash&ip=ip`

"The ip field is optional and when present should be the IP address of the connecting player; it is the one that originally initiated the session request. The notchian server includes this only when prevent-proxy-connections is set to true in server.properties."

https://wiki.vg/Protocol_Encryption

Code for reference: https://github.com/VelocityPowered/Velocity/blob/master/proxy/src/main/java/com/velocitypowered/proxy/connection/client/LoginSessionHandler.java#L54

**Comment by astei** [comment]
#307 is now merged in, closing this issue.
