### ISSUE TITLE
Connection Timeout: "Unable to authenticate with Mojang"

### ISSUE THREAD

**Issue by WesternPine** [VelocityPowered/Velocity#297]
Granted I'm not on the best internet, I am still getting a timeout issue while connecting to my local Velocity server, that prevents me from joining. Additionally, I have no plugins running, and am getting a timeout error after 5 seconds.

Velocity Build: [DEV] 1.1.0
The Error: https://pastebin.com/NvyKWVVf
My Internet At The Time: https://www.speedtest.net/result/9340327962 (Should suffice)
My Configuration File: https://pastebin.com/CvdBcWCS

Additionally, I wasn't able to replicate the issue on Bungeecord, and it seems random.

**Comment by astei** [comment]
The Netty DNS resolver can have issues sometimes, and you may be running into one of those issues.

I would suggest using a different resolver, `1.1.1.1` (Cloudflare) or Google Public DNS will probably work better than whatever your router is using right now.

**Comment by WesternPine** [comment]
Will do! I'll give it a shot in the morning. Is it possible that it will still resolve the issue if I apply these changes to my PC instead of my router?

**Comment by WesternPine** [comment]
Issue was resolved by using a different DNS.
