### ISSUE TITLE
Installing DiscardHandler throws Exception

### ISSUE THREAD

**Issue by Gabik21** [VelocityPowered/Velocity#302]
Installing the `DiscardHandler` can apparently happen without a minecraft decoder in the pipeline producing this exception: https://gist.github.com/Gabik21/fa9c3acdb1bf3368b5a0c8c2545a7331

Since this is a workaround and the original issue was fixed in netty, I guess we can also consider removing this all together.

**Comment by astei** [comment]
The original issue was mitigated in Netty but not to the extent I'd prefer. I'll look into this issue when I have more time available.

**Comment by astei** [comment]
1d9b7d3fdb (present in an experimental branch) will fix this issue.
