### ISSUE TITLE
Is there an API to execute command from the end servers?

### ISSUE THREAD

**Issue by wysohn** [VelocityPowered/Velocity#306]
For example, in BungeeCord, it natively supports executing commands (/server, etc) through the PluginMessageChannel, but as far as I go, I don't find anything similar in Velocity.
[BungeeCord example](https://www.spigotmc.org/wiki/bukkit-bungee-plugin-messaging-channel/)

I have a user who wants to use Velocity as a proxy server and using my plugin in the end server. The plugin can send few commands like `/server` to the BungeeCord since it has the built-in channel, "BungeeCord," yet I wonder if I can do the same with Velocity.

At least it's not in the documentation, so please understand me if I missed it somewhere.

Please let me know if there's any information about it.

Thank you!

**Comment by STG-Allen** [comment]
Velocity supports the Bungee messages in 1.1.0 or via BungeeQuack

**Comment by wysohn** [comment]
Thank you for the quick response!

For future reference: [BungeeQuack](https://forums.velocitypowered.com/t/bungeequack-use-the-plugins-you-love-with-velocity/14)
