### ISSUE TITLE
Server connection order based on version protocol

### ISSUE THREAD

**Issue by LuxusDarkangel** [VelocityPowered/Velocity#311]
Velocity has great Forge support, but managing a network with different modpacks is a really rough job right now.

According to #191, there's no way to fallback to another server if FML handhsake fails, preventing the use of server connection order to avoid lobbys. But, could Velocity check the client's protocol and forward the player to the first server with the same protocol?

If this can be done, if we have Server 1 with a 1.12.2 modpack, Server 2 with a 1.7.10 modpack and a player tries to connect with the 1.7.10 modpack, he can be forwarded directly to the 1.7.10 server instead of getting rejected on the 1.12.2 server.

**Comment by astei** [comment]
I would much prefer this to be a plugin, and if it turns out to be widely used, that would make this a prime candidate for inclusion into Velocity proper. But as it presently stands, this is a niche case that I feel Velocity wouldn't be able to do a good job with.

> but managing a network with different modpacks is a really rough job right now

Never mind the fact that there is almost no chance of Forge 1.13+ support due to breaking changes on the Forge end and lack of time/resources to push that forward.

**Comment by LuxusDarkangel** [comment]
You're right, this should be a plugin as it's probably too niche to be a main feature. Apparently something like this does indeed exist as a [BungeeCord plugin](https://github.com/Phoenix616/VersionConnector), but sadly there's nothing equivalent for Velocity

> Never mind the fact that there is almost no chance of Forge 1.13+ support due to breaking changes on the Forge end and lack of time/resources to push that forward.

I think Fabric is probably the way to go right now. Managing modded servers (let alone networks) was never a flower path though.

**Comment by astei** [comment]
Some people have recently requested we skip servers that are down in the `try` list. I feel like I'll have to give the same response here and close this issue for good, as it will only sow more confusion.

I think plugins are better placed to modify connection order. Velocity already has a difficult-enough time supporting a wide range of Minecraft versions (each becoming successively more complicated), and bolting on complex server selection logic distracts us from the goal of delivering a high-performance, scalable, highly-compatible proxy.
