### ISSUE TITLE
Format issue on [servers] using whitespace

### ISSUE THREAD

**Issue by JbPasquier** [VelocityPowered/Velocity#320]
Using this on my `velocity.toml`:

```toml
[servers]
"Invalid Name" = "127.0.0.1:1234"

try = [
  "Invalid Name"
]
```

Will work on first velocity start, but it'll regenerate the file this way:

```toml
[servers]
Invalid Name = "127.0.0.1:1234"

try = [
  "Invalid Name"
]
```

And will not work anymore.

```
Unable to read/load/save your velocity.toml. The server will shut down.
java.lang.IllegalStateException: Invalid key on line 41: Invalid Host
```

**Comment by Leymooo** [comment]
https://github.com/VelocityPowered/Velocity/blob/master/proxy/src/main/java/com/velocitypowered/proxy/config/AnnotatedConfig.java#L215
Looks like also need to check for space here 
 `if ((key.contains(".") || key.contains(" ")) && ..)`

**Comment by astei** [comment]
Thanks, this is now fixed.

**Comment by astei** [comment]
A permanent fix for this is now in place for the next version of Velocity.
