### ISSUE TITLE
Fire ProxyShutdownEvent before closing the scheduler / event bus

### ISSUE THREAD

**Issue by lucko** [VelocityPowered/Velocity#322]
Plugins should be given a chance to gracefully halt their activity before the scheduler and event bus are shutdown.

Assuming you agree, I'm happy to PR, just let me know which branch to target. :)

See: lucko/LuckPerms#2415

**Comment by astei** [comment]
I think that would be reasonable, feel free to PR.

**Comment by lucko** [comment]
Which branch?

**Comment by astei** [comment]
I consider this a bug, apply to both `master` and `dev/1.1.0`.
