### ISSUE TITLE
Configuration API for plugins

### ISSUE THREAD

**Issue by Proximyst** [VelocityPowered/Velocity#326]
**Describe the feature request in simple terms**
The Velocity API should contain some API for creating plugin configurations.

**Propose a way to achieve this**
Ideally, one would just be able to hand a class to some factory which in turn reads the configuration from the plugin's data directory. An example could be an injected `ConfigFactory` into the plugin, which can take a `Class<? extends Configuration>` which requires a couple fields such as the configuration name.

I noticed there is [`AnnotatedConfig`](https://github.com/VelocityPowered/Velocity/blob/35b78331fbdc4c161ef47fa7a6c514c2fcab692b/proxy/src/main/java/com/velocitypowered/proxy/config/AnnotatedConfig.java) which could very well work great for this.

**Are there any alternative ways this feature could be achieved?**
For one, Velocity could simply copy the YAML configuration API present in BungeeCord & Bukkit, but as most who have migrated to Velocity can confirm, it is quite simply awful.

**Comment by astei** [comment]
`AnnotatedConfig` is ugly and doesn't even produce correct TOML in a number of cases.

For Velocity 1.1.0, the solution is to use [Configurate](https://github.com/SpongePowered/Configurate/wiki) which nicely handles everything you might need configuration-related.

**Comment by astei** [comment]
Configurate doesn't handle TOML yet but @zml2008 is working to be working on a parser for Configurate 4.0.

**Comment by Proximyst** [comment]
Anything that helps me write the configuration & test it while a TOML supporting version is underway helps. Thank you! :)

**Comment by astei** [comment]
Configurate supports formats other than TOML such as YAML and JSON, those might work for you for now.

**Comment by zml2008** [comment]
just to be clear -- i expect toml will only make it in for 4.1 or so, my goal for 4.0 is to lay the groundwork for more formats, using json5 as a simple format to validate the design.

**Comment by Proximyst** [comment]
Configurate makes it terrifyingly easy to just swap the format later on, so I'm sure that's no problem! Thank you for the work :)
