### ISSUE TITLE
Hex colors cause packet decode error

### ISSUE THREAD

**Issue by TheDutchMC** [VelocityPowered/Velocity#328]
Hi,

## Description
With 1.16 hex colors were introduced. In Bukkit plugins these are applied using the bungee API. E.g:
```ChatColor.of("#00ff00")```, from net.md_5.bungee.api.ChatColor. However Velocity doesn't like this, and will kick the player that has this color applied.

## Steps to reproduce
1. Apply the color as shown above, e.g to the DisplayName (```Player.setDisplayName(ChatColor.of("#00ff00") + Player.getName() + ChatColor.WHITE);```)

## Expected behaviour
Velocity knows how to work with this

## Stacktraces
- [https://pastebin.com/JdM5dqEg]()
- [https://pastebin.com/JdM5dqEg](url)

## Environment
MC Version: 1.16.1
Paper version: git-Paper-89 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)
Velocity version: 1.1.0-SNAPSHOT (git-7fd76962-b148)
OS: Ubuntu 18.04 LTS
Java: openjdk-8_251

## Plugins installed
- WorldEdit (a dependency)
- UHCPlus (my own plugin, can be found here: [https://github.com/TheDutchMC/uhcplus](url), error occurs after joining a team and running /uhcp start)

**Comment by astei** [comment]
You are on an outdated version of Velocity 1.1.0, please update to the latest build on Jenkins.

**Comment by TheDutchMC** [comment]
Now on build 159, issue appears to be solved.
