### ISSUE TITLE
Should buffer packets in loop and then flush once

### ISSUE THREAD

**Issue by robinbraemer** [VelocityPowered/Velocity#336]
https://github.com/VelocityPowered/Velocity/blob/7ab56d0ca06eadf60a889577e1bcea1e53787640/proxy/src/main/java/com/velocitypowered/proxy/connection/client/ClientPlaySessionHandler.java#L520-L521

**Comment by astei** [comment]
The small efficiency gain here is minimal at best, there are bigger gains to be had elsewhere
