### ISSUE TITLE
CommandResult.command() forwards the old command to server(s)

### ISSUE THREAD

**Issue by TheRealSpeedy** [VelocityPowered/Velocity#348]
CommandResult.command() forwards the old command to the servers(s) while looping the new one back to the proxy

**Comment by astei** [comment]
Can you please show me your code?

**Comment by TheRealSpeedy** [comment]
`event.setResult(CommandExecuteEvent.CommandResult.command(getReplacementCommand(args[1])));`

getReplacementCommand() returns a String with the new command

**Comment by astei** [comment]
I'm afraid that is insufficient, show me the full code for the listener.

**Comment by TheRealSpeedy** [comment]
Main:
`package red.rainbow.rainbowhelp;

import com.google.inject.Inject;
import com.velocitypowered.api.command.CommandManager;
import com.velocitypowered.api.event.Subscribe;
import com.velocitypowered.api.event.proxy.ProxyInitializeEvent;
import com.velocitypowered.api.plugin.Plugin;
import com.velocitypowered.api.proxy.ProxyServer;
import org.slf4j.Logger;
import red.rainbow.rainbowhelp.CmdExecFollower;

@Plugin(
        id = "help",
        name = "RainbowHelp",
        version = "1.0",
        description = "Provides /help command.",
        url = "https://rainbow.red",
        authors = {"RainbowSpeedy"}
)
public class Help {

    public static final String pf = "§8»§r ";

    @Inject
    private Logger logger;

    @Inject
    private CommandManager cmdMgr;

    @Inject
    private ProxyServer server;

    @Subscribe
    public void onProxyInitialization(ProxyInitializeEvent event) {
        server.getEventManager().register(this, new CmdExecFollower());
    }
}`

Listener:
`package red.rainbow.rainbowhelp;

import com.velocitypowered.api.command.CommandSource;
import com.velocitypowered.api.event.Subscribe;
import com.velocitypowered.api.event.command.CommandExecuteEvent;

import java.util.Arrays;

import static red.rainbow.rainbowhelp.StringProvider.*;

public class CmdExecFollower {

    @Subscribe
    public void afterCommandExecution(CommandExecuteEvent event) {
        CommandSource source = event.getCommandSource();
        String[] args = event.getCommand().split(" ");

        if (args.length == 1) {
            source.sendMessage(net.kyori.adventure.text.TextComponent.of(getMainscreen()));
        } else if (args.length == 2) {

            String category = args[1];

            if (Arrays.stream(getAllCategories()).anyMatch(cat -> cat.equalsIgnoreCase(category))) {
                if (getScreenForCategory(category) == null) {
                    event.setResult(CommandExecuteEvent.CommandResult.command(getReplacementCommand(args[1])));
                } else {
                    source.sendMessage(net.kyori.adventure.text.TextComponent.of(getScreenForCategory(category)));
                }
            } else {
                source.sendMessage(net.kyori.adventure.text.TextComponent.of(getMainscreen()));
            }
        }
    }
}`

**Comment by astei** [comment]
I took a look at the relevant Velocity code, going through it in a debugger. I can't reproduce this issue. It's probably more likely this is a bug in your code. I suggest you debug your listener.
