### ISSUE TITLE
Help debugging "A packet did not decode successfully (invalid data)"

### ISSUE THREAD

**Issue by azokthedefiler1** [VelocityPowered/Velocity#349]
## Problem
I'm getting this error when entering certain locations on my modded server:

`[00:41:54 INFO]: [server connection] azokthedefiler1 -> dwr1 has connected`
`[00:42:13 ERROR]: [server connection] azokthedefiler1 -> dwr1: exception encountered in com.velocitypowered.proxy.connection.backend.BackendPlaySessionHandler@16432293
com.velocitypowered.proxy.util.except.QuietDecoderException: A packet did not decode successfully (invalid data). If you are a developer, launch Velocity with -Dvelocity.packet-decode-logging=true to see more.`
`[00:42:13 INFO]: [server connection] azokthedefiler1 -> dwr1 has disconnected`

Adding "-Dvelocity.packet-decode-logging=true" to java when starting velocity does nothing. There above error is replaced with:

`[00:10:30] [Netty epoll Worker #1/INFO]: [server connection] azokthedefiler1 -> dwr1 has connected`
`[00:10:33] [Netty epoll Worker #1/INFO]: [server connection] azokthedefiler1 -> dwr1 has disconnected`

Minecraft server console logs error as:

`[00:58:02] [Server thread/INFO] [minecraft/DedicatedServer]: azokthedefiler1 joined the game`
`[00:58:02] [Server thread/INFO] [minecraft/NetHandlerPlayServer]: azokthedefiler1 lost connection: Internal Exception: java.io.IOException: Connection reset by peer`
`[00:58:02] [Server thread/INFO] [minecraft/DedicatedServer]: azokthedefiler1 left the game`

## Version
Velocity: velocity-proxy-1.1.0-SNAPSHOT-all.jar build #206

## Next steps
* How do I enable debugging to get more info about what is happening here?
* What other info do you need to fix this issue?

**Comment by astei** [comment]
You did not provide sufficient information. To help us figure out the issue, please provide the following:

* What backend server is the issue happening on - is it Forge or Fabric? (It seems you are using a modded server.)
* What mods do you have installed?

In addition, please make sure the `-Dvelocity.packet-decode-logging=true` flag is before the `-jar`, i.e. `java -Dvelocity.packet-decode-logging=true -jar velocity.jar`. Also please post full logs instead of truncated logs for Velocity, it is hard to tell if you got an error on the second try.

**Comment by azokthedefiler1** [comment]
## MC Server Info
Forge: forge-1.12.2-14.23.5.2838-universal.jar
Minecraft: 1.12.2 w/updated Netty version 4.1.49
SpongeForge: spongeforge-1.12.2-2838-7.2.0.jar


## Installed Mods
1_spongeforge-1.12.2-2838-7.2.0.jar (renamed to be first)
AkashicTome-1.2-12.jar
ancientwarfare-1.12.2-2.7.0.772.jar
animania-1.12.2-1.7.3.jar
Armourers-Workshop-1.12.2-0.50.1.jar
Atum-1.12.2-2.0.17.jar
AutoRegLib-1.3-32.jar
Baubles-1.12-1.5.2.jar
BetterCombat-1.12.2-1.5.6.jar
BetterFps-1.4.8.jar
BetterRecords-1.12.2-1.6.2.jar
biggerpacketsplz-since1.8-1.2.jar.disabled
BiomesOPlenty-1.12.2-7.0.1.2444-universal.jar
blockcraftery-1.12.2-1.3.1.jar
Botania+r1.10-363.jar
champions-1.12.2-1.0.11.8.jar
CodeChickenLib-1.12.2-3.2.3.358-universal.jar
CompatSkills-1.12.2-1.17.0.jar
conarm-1.12.2-1.2.5.9.jar
CraftStudioAPI-universal-1.0.1.95-mc1.12-alpha.jar
CraftTweaker2-1.12-4.1.20.574.jar
CustomNPCs_1.12.2-(01Oct19).jar
DamageIndicatorsMod-3.5.1.jar
dooglamooworlds-1.12.2-1.1.7.jar
DynamicSurroundings-1.12.2-3.6.0.2.jar
DynamicTrees-1.12.2-0.9.8.jar
DynamicTreesBOP-1.12.2-1.4.1e.jar
ElectroblobsWizardry-4.2.11-MC1.12.2.jar
enchcontrol-1.12.2-1.1.5-0.jar
Exotic+Birds+1.12.2-3.2.0.jar
extrautils2-1.12-1.9.9.jar
foamfix-0.10.10-1.12.2.jar
Forgelin-1.8.4.jar
fossilsarcheology-8.0.4.jar
furniture-6.3.1-1.12.2.jar
fusion-1.12.2-2.4.1.11.jar
heroicarmory-1.2.0.jar
Hwyla-1.8.26-B41_1.12.2.jar
iceandfire-1.9.1-1.12.2.jar
inventorypets-1.12-2.0.4.jar
IronBackpacks-1.12.2-3.0.8-12.jar
ironchest-1.12.2-7.0.72.847.jar
jei_1.12.2-4.15.0.296.jar
kinetic_anti-cheat-12.2.2.jar
LagGoggles-1.12.2-5.8-132.jar
llibrary-1.7.19-1.12.2.jar
Mantle-1.12-1.3.3.55.jar
multimob-1.0.5.jar
mysticallib-1.12.2-1.5.0.jar
NBTEdit-0.7.jar
OpenBlocks-1.12.2-1.8.1.jar
OpenModsLib-1.12.2-0.12.2.jar
OreLib-1.12.2-3.6.0.1.jar
outfox-0.1.5-mc1.12.2.jar
Pam's+HarvestCraft+1.12.2zg.jar
Pam's+Simple+Recipes+1.12.2c.jar
plustic-8.0.1.0.jar
primitivemobs-1.2.3a.jar
Reskillable-1.12.2-1.13.0.jar
RoguelikeDungeons-1.12.2-1.8.0.jar
Schematics-1.12.2.12.jar
ServerTabInfo-1.12.2-1.2.6.jar
sideslabs-1.12.2-1.1.jar
simplecore-1.12.2-1.7.3.4.jar
simpleores-1.12.2-1.11.2.2.jar
SimpleTcon-3.0b.jar
tc6aspects4jei-0.0.2a.jar
TConstruct-1.12.2-2.13.0.183.jar
tellme-1.12.2-0.7.0-dev.20190610.165828.jar
Thaumcraft-1.12.2-6.1.BETA26.jar
ThaumicJEI-1.12.2-1.6.0-27.jar
TickCentral-2.6.jar
TinkersExtras-1.12.2-1.1.0.jar
TombManyGraves-1.12-4.2.0.jar
tweakersconstruct-1.12.2-1.5.3.jar


## Installed Sponge Plugins
ActiveTime-s7.1-v1.4.3.jar
BuycraftX.jar.disabled
CatClearLag-0.9.5.1.jar
ClearMob-1.12.2-2.2.3.jar
CmdControl-s7.1-v1.2.0.jar
CmdScheduler-s7.1-v1.1.1.jar
ExpBank-1.0.jar
griefprevention-1.12.2-4.3.0.692.jar
InvSync-0.6.19.318.jar
iplog-0.2.1.jar
LangSwitch-1.6.1.jar
LuckPerms-Sponge-5.1.73.jar
MagiBridge-API7-2.10.3.jar.disabled
Maintenance-3.0.5.jar
MeeM-1.0.jar
MegaMenus-0.7.jar
MMCReboot-2.3.2-API-7.jar
MMCRestrict-1.7.1-API-7.jar
Nucleus-1.14.6-S7.1-MC1.12.2-plugin.jar
PlaceholderAPI-4.4.jar
PlayerQueueService-1.1.jar
prism-f456812-all.jar
projectcore-7.2.0-0.3.0.jar
projectportals-7.2.0-0.15.2.jar
RBounty-2.0.4.jar
SafeTrade-1.12.2-2.0.4-SPONGE.jar
serial-key.jar
ServerListPlus-3.4.7-Universal.jar
SlashDiscord-1.4.0.jar
SleepVote-1.1.0-S7.0.jar
spark-1.4.2.jar
statusprotocol-0.3.jar
TabManager-2.1.3-S7.0-MC1.12.2.jar
TESqlHelper-0.1.1-TE1.8.1.jar.disabled
ThaumcraftFocusBan-0.1-Release.jar
TotalEconomy-1.8.2.jar
UltimateChat-1.8.8-b196-Universal.jar
UltimateChat-JDA.jar.disabled
VillagerShops-2.5.jar
VirtualTool-1.12.2-5.5-S7.1.0-STABLE.jar
worldedit-sponge-api7.1.0-6.1.10-SNAPSHOT-dist.jar
WorldRebuilder-1.1.1.jar


## Velocity Run
try-1: java -jar velocity-proxy-1.1.0-SNAPSHOT-all.jar
try-2: java -Dvelocity.packet-decode-logging=true -jar velocity-proxy-1.1.0-SNAPSHOT-all.jar


## MC Server Run
/usr/bin/java -Xms4G -Xmx4G -Dfml.doNotBackup=true -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true -jar custom.jar nogui


## Known Info
* 1 location found is an Ancient Warfare structure with VShop NPC's, causes "invalid data"
* 1 location found is player built structure with VShop NPC's, causes "invalid data"
* Server world spawn location is player built with VShop NPC's, does not cause "invalid data"
* Invalid data occurs whether biggerpacketsplz-since1.8-1.2.jar is enabled/loaded or not
* Connection problem only occurs when proxied through Velocity

Most of the world works just fine, just certain areas, 2 that I've found so far, cause the "invalid data" error. Let me know if you need anything else.

[log-files.zip](https://github.com/VelocityPowered/Velocity/files/5032209/log-files.zip)

**Comment by astei** [comment]
So I suppose we're looking at _two_ issues here. First, _why_ Velocity isn't giving us useful debug information for us, and secondly the _actual_ issue we're looking at.

**Comment by astei** [comment]
@azokthedefiler1 Please try the latest Velocity 1.1.0 build with `-Dvelocity.packet-decode-logging=true`. I have fixed the issue that caused us to not get useful debugging information.

**Comment by azokthedefiler1** [comment]
Ok, now I got something that hopefully makes sense for you.

[try-3-velocity-debug-flags.log](https://github.com/VelocityPowered/Velocity/files/5036918/try-3-velocity-debug-flags.log)

**Comment by astei** [comment]
Thanks. It looks like this is a Velocity bug, I will go ahead and take a closer look once I've got a 1.16.2-pre3 update for Velocity ready.

**Comment by azokthedefiler1** [comment]
Sounds good to me. Let me know if you need anything else.

**Comment by astei** [comment]
Let me know if this fixes the issue.

**Comment by azokthedefiler1** [comment]
Didn't work.

[try-4-velocity-debug-flags.log](https://github.com/VelocityPowered/Velocity/files/5037915/try-4-velocity-debug-flags.log)

I downloaded the latest build (211) from Jenkins.

**Comment by astei** [comment]
It looks like you have a `show_item` or `show_entity` hover item being added to player list items. Unfortunately, Adventure (the text library) doesn't currently handle this situation without Velocity providing logic to fill in the gaps.

Since this is in the tab list, it's most likely a tab plugin is injecting this component. The best workaround I can give is to not use these hover events in a tab list (it's unlikely they will be useful anyway).

**Comment by azokthedefiler1** [comment]
The only mod I'm using that modifies the tab list is ServerTabInfo-1.12.2-1.2.6.jar. I'll try removing that and see if the error stops.

**Comment by astei** [comment]
NPCs can also affect this. You mention the error mostly occurs where "VShop NPCs" are. You may want to consider removing it too.

**Comment by azokthedefiler1** [comment]
I thought that too, but I have VShop NPC's in other areas that are not affected. I'm not sure what the difference would be there except for different items/block in their inventory. I'll give it shot anyway and let you know if it worked.

**Comment by astei** [comment]
I've prepared a potential fix to the issue without you making changes on your end. [Download this ZIP](https://github.com/VelocityPowered/Velocity/files/5038713/velocity-proxy-1.1.0-SNAPSHOT-all.zip), unzip it, and try the JAR inside and see if it fixes the issue.

**Comment by azokthedefiler1** [comment]
That didn't work, and the error message seems different too.

[try-5-velocity-debug-flags.log](https://github.com/VelocityPowered/Velocity/files/5038769/try-5-velocity-debug-flags.log)

I also tried removing the VillagerShops plugin and ServerTabInfo mod earlier but neither had any effect.

**Comment by astei** [comment]
Please try this: [velocity-proxy-1.1.0-SNAPSHOT-all.zip](https://github.com/VelocityPowered/Velocity/files/5038784/velocity-proxy-1.1.0-SNAPSHOT-all.zip)

This includes the offending SNBT as a debug. Perhaps we've stumbled across an issue with a plugin/mod.

**Comment by azokthedefiler1** [comment]
[try-6-velocity-debug-flags.log](https://github.com/VelocityPowered/Velocity/files/5038811/try-6-velocity-debug-flags.log)

"Johny" is definitely a VShop NPC, though I can't say what is special about that one vs. others that are working fine. Even with the plugin disabled (renamed not .jar) it still crashes. I'm going to try recreating that NPC to see if it makes a difference.

Do you think this debug is enough to take back to the author of VillagerShops?

**Comment by astei** [comment]
Let's do another go at some more debugging. I'm not yet ready to convince myself if this is an issue in Velocity, Adventure (the text library we use), or some mod or plugin on your server. I'm currently leaning towards the latter but let's try and get some debug to rule out Adventure.

[velocity-proxy-1.1.0-SNAPSHOT-all.zip](https://github.com/VelocityPowered/Velocity/files/5038869/velocity-proxy-1.1.0-SNAPSHOT-all.zip)

**Comment by azokthedefiler1** [comment]
You're right. I started looking into the NPC's causing problems and they are all "sponge:human". I picked an empty spot to "/summon sponge:human" and crashed instantly. The log line is as follows:

[21:28:37 INFO]: Hover item SNBT: {name:"entity.human.name",id:"3be2046a-4a11-41e5-a4ad-55dcd44092c1"}

So whatever you're using to parse (I think I'm using the correct term here) does not like sponge:human for some reason.
I have not tried the latest ZIP you attached, but I will try that now and post back the log in a few minutes.

**Comment by azokthedefiler1** [comment]
Here is the latest log with the "non-VShop NPC" entity sponge:human.

[try-7-velocity-debug-flags.log](https://github.com/VelocityPowered/Velocity/files/5039011/try-7-velocity-debug-flags.log)

**Comment by astei** [comment]
Ok, I think I know what’s up. This is likely a Velocity problem. I will continue working on this in the morning.

**Comment by azokthedefiler1** [comment]
Sounds good. Thanks for your efforts.

**Comment by astei** [comment]
Give this a try: [velocity-proxy-1.1.0-SNAPSHOT-all.zip](https://github.com/VelocityPowered/Velocity/files/5041017/velocity-proxy-1.1.0-SNAPSHOT-all.zip)

I think I got the issue.

**Comment by azokthedefiler1** [comment]
That looks like it's working! I'm able to join the server where I spawned the previous sponge:human. I'm going to test the other locations known to cause the issue and report back shortly.

**Comment by azokthedefiler1** [comment]
I just finished checking all the shops, and anything I could of that might be a problem, and everything seems to be working great now!

Which build # should be downloading to get the official version (assuming the zips are not merged yet)?

**Comment by astei** [comment]
The builds you've been using is a branch of Velocity with 1.16.2 support. This branch will be merged in once 1.16.2 support is merged in (likely this Tuesday).

**Comment by azokthedefiler1** [comment]
Great! I'll make a note to check back next Wednesday then. Thanks for all your help!
