### ISSUE TITLE
[Discussion] Command permission updates

### ISSUE THREAD

**Issue by MrIvanPlays** [VelocityPowered/Velocity#352]
Continuation discussiuon for the problems of current command api handling described in #350 

I've looked at what bukkit does in order to dynamically update commands of the client. What they basically do is whenever some change happens (player gets moved to other world, player's permissions change, player gets teleported somewhere), they resend the packet. Velocity already handles incoming AvailableCommands from backend server changes, we just need to handle it for velocity permission changes.

## What I have in mind

Keep track of the root node that the backend server sends, and whenever a proxy level permission change happens, resend the packet. Have a special field in the packet so that we can determine if the incoming packet is coming from the backend server or the proxy so that no stackoverflows happen. 

I'd like to see your ideas before doing anything.

**Comment by hugmanrique** [comment]
Eh, extract the current logic from the `AvailableCommands` packet handler and call it for every online player when a command node is registered/unregistered (only if the `injectProxyCommands` option is `true`). I don't know how I would handle permission changes though.

**Comment by MrIvanPlays** [comment]
you do realize commands are registered before velocity can accept connections?

**Comment by hugmanrique** [comment]
Plugins are free to register/unregister commands whenever they like.

**Comment by MrIvanPlays** [comment]
Yeah but most of the cases registering wouldn't work as expected as it is done in ProxyInitializeEvent which is called before velocity can accept connections

**Comment by hugmanrique** [comment]
Of course, if the registration is done when no players are online (e.g. on initialization), no extra logic is required. What I'm saying is there's cases when such logic is required.

**Comment by A248** [comment]
It's not expected or required to register commands during the ProxyInitializeEvent. Plugins can do so at any later time.

**Comment by MrIvanPlays** [comment]
okay sure we can also handle it whenever a command is registered/unregistered if the proxy can accept connections and connections > 0 what i'm more interested is how we would listen for permission change. velocity calls PermissionSetupEvent whenever the player is initialized and when you run a permissions plugin say luckperms whatever permission change works but there's no way to listen for that permission change except explicitly calling hasPermission multiple times

**Comment by astei** [comment]
I'm vetoing this based solely on memory consumption concerns.

In 1.16.2-pre3, a copy of the root command node sent by a vanilla server is already over 600KB. Obviously, amortized (due to potential string deduplication) this is likely to be smaller, but having to allocate 600KB of node data per player means that almost half the heap will be taken up to cover an edge case that most people will not care much about.

If there is a _solid_ justification for adding this, and there is a way to implement this that does not drastically increase memory usage, I may consider it. But at the moment, the memory usage required is a no-go for me.
