### ISSUE TITLE
About player chat messages

### ISSUE THREAD

**Issue by mcqwy** [VelocityPowered/Velocity#355]
How can I send a clickable chat message to players?
For example, if a player clicks a message on the client, it will be automatically entered into the chat bar?
Or click on the message to execute the command?
I tried to use: `player.sendMessage(TextComponent.of(mess));`, but the message received by the client was not clickable.
What can I do to have the effect of the figure below?
![1234](https://user-images.githubusercontent.com/38318368/90481311-227fc700-e164-11ea-843a-08fe291c8c9b.png)
Sorry, my English is not very good, I hope you can understand.

**Comment by STG-Allen** [comment]
Have a look at the TextEvent. You'll have to make a 
```
TextComponent.builder()
``` to use them

**Comment by mcqwy** [comment]
Thank you very much. It's working very well now.

**Comment by astei** [comment]
Closing this issue. This issue tracker is not a general discussion forum, we have https://forums.velocitypowered.com and Discord for that.
