### ISSUE TITLE
per server MOTD/player count (forced hosts)

### ISSUE THREAD

**Issue by GNUGradyn** [VelocityPowered/Velocity#362]
I am using velocity to allow 2 separate minecraft servers to connect via 2 separate domains. I've configured it to do this via forced hosts. How can I set an MOTD for each domain? How can I isolate player count?

```
[forced-hosts]
# Configure your forced hosts here.
"gradyn.com" = [
  "gradyn"
]
"badlugi.com" = [
  "hbivanilla"
]
```

```
[servers]
# Configure your servers here. Each key represents the server's name, and the value
# represents the IP address of the server to connect to.
gradyn = "127.0.0.1:25566"
hbivanilla = "127.0.0.1:42068"
```

**Comment by astei** [comment]
At the moment this functionality is not supported.

**Comment by astei** [comment]
If desired, a plugin can add this functionality.

**Comment by astei** [comment]
I just realized: since you only use one server per forced host, you can use ping passthrough on Velocity 1.1.0 to accomplish this. It'll use the virtual host given by the client.

**Comment by 0Chameleon0** [comment]
I am interested in this also. How do I use ping passthrough? I cant see an option in the config for this.

**Comment by hugmanrique** [comment]
Upgrade to 1.1.0 and change the following https://github.com/VelocityPowered/Velocity/blob/65cab85b50bb60f9fc855132db5e09408945879e/proxy/src/main/resources/default-velocity.toml#L63

**Comment by 0Chameleon0** [comment]
Thankyou, Problem resolved, much appreciated 👍

**Comment by GNUGradyn** [comment]
This is an acceptable workaround
