### ISSUE TITLE
Improve some proxy disconnect messages

### ISSUE THREAD

**Issue by MatrixTunnel** [VelocityPowered/Velocity#58]
Here are the various messages that could be improved

> Connect to the proxy with no online servers behind it
https://i.imgur.com/1nM3OAt.png

> Forcibly close server behind the proxy while connected
https://i.imgur.com/D4E8Zn0.png

**Comment by astei** [comment]
This isn't a bug. Velocity is doing the right thing here - this is also consistent with what BungeeCord does.

I'm rewording the title of this bug to be less misleading.

**Comment by MatrixTunnel** [comment]
Updated the issue to make it more accurate

**Comment by ChefMC** [comment]
Why it log stacktrace to console? Just disconnect message will be enough

![image](https://github.com/PaperMC/Velocity/assets/3519015/f83256f3-07c3-4068-aee3-3e359198fed2)

Then imagine 1000 players will disconnect due to backend server stop. Velocity will be full of 1000 stacktraces and will spam console and log with 100 000 lines! _Disk space left the chat..._

**Comment by 4drian3d** [comment]
> Why it log stacktrace to console? Just disconnect message will be enough
> 
> ![image](https://user-images.githubusercontent.com/3519015/262509057-f83256f3-07c3-4068-aee3-3e359198fed2.png)
> 
> Then imagine 1000 players will disconnect due to backend server stop. Velocity will be full of 1000 stacktraces and will spam console and log with 100 000 lines! _Disk space left the chat..._

If you want to avoid those useful stacktraces, you can use a plugin like LogFilter https://modrinth.com/plugin/logfilter

**Comment by ChefMC** [comment]
It's a crutch. Which creating excessive overhead

**Comment by ChefMC** [comment]
It shouldn't be done this way at all. 

Stacktraces when player join? Stacktraces when player move? Stacktraces when backend server enabled? Stacktraces, Stacktraces, Stacktraces, Stacktraces, Stacktraces, Stacktraces, Stacktraces, Stacktraces, Stacktraces, Stacktraces, Stacktraces, Stacktraces...

**Comment by electronicboy** [comment]
shortening down the more "expected" ones is on my todo list, but, I don't wanna make it too much of a pita for diagnosing actual bugs

**Comment by ChefMC** [comment]
Just add a startup flag please, or config option. Because now when 1000 players will disconnect due to backend server stop, Velocity will be full of 1000 stacktraces and will spam console and log with 20 000 - 50 000 lines at once. It's also bad for disk space where log files are stored
