### ISSUE TITLE
Localization support

### ISSUE THREAD

**Issue by astei** [VelocityPowered/Velocity#60]
Use Mojang messages where possible, otherwise provide our own localizations.

**Comment by Zaxar163** [comment]
I advice you to use ResourceBundle, but if you need be faster contact me, I create pull request with faster ResourceBundle. Also it make translations easy.

**Comment by astei** [comment]
Deferring for Velocity 2.0.0.

**Comment by astei** [comment]
It's finally here (with c0b6f46 and 69cba59).
