### ISSUE TITLE
Velocity Server Communication API

### ISSUE THREAD

**Issue by astei** [VelocityPowered/Velocity#68]
Essentially should cover the same sort of ground the BungeeCord plugin messaging channel does today.

**Comment by kashike** [comment]
I'd love to see this use player unique ids instead of player names, too.

**Comment by lucko** [comment]
If you do decide to go down the "plugin message" style route, I'd like to suggest some sort of system that allows you to pair requests/responses together.

One thing in particular I dislike about the BungeeCord system is that the response cannot be easily matched to the corresponding request.

The sanest approach I've found is to store a list of callbacks to be tested as responses are received.

e.g. https://github.com/lucko/helper/blob/ed24ea78bd7d2fb73b3a06ebf32ef2d74d8576bb/helper/src/main/java/me/lucko/helper/messaging/bungee/BungeeCordImpl.java#L122-L161

followed by an test per subchannel to see if the response is appropriate.

e.g. https://github.com/lucko/helper/blob/ed24ea78bd7d2fb73b3a06ebf32ef2d74d8576bb/helper/src/main/java/me/lucko/helper/messaging/bungee/BungeeCordImpl.java#L519-L522

One potential means to make this more seamless is to allow requests to contain some sort of "identifier", which will be returned along with the response.


e.g. a request may look like:

```json
{
    "identifier": "a9091b34-16dd-4312-8f54-9ab464634372",
    "request": {
        "type": "player_count",
        "target": "survival"
    }
}
```

to which the proxy may respond with:

```json
{
    "identifier": "a9091b34-16dd-4312-8f54-9ab464634372",
    "response": {
        "value": 37
    }
}
```

This would allow a request/response style system to be easily wrapped by an future based API on the client.

**Comment by astei** [comment]
I've been working on this. Here's my initial draft for the Velocity plugin messaging API: https://docs.google.com/document/d/1aAO0H2g91WTn0VAl3IuYql8YtPEOQBaCXWNHw9NKqlg/edit?usp=sharing

My main issue is the the forward message. This is not really how I'd want to implement it. Personally I would've excluded this and suggested Redis PubSub or RabbitMQ, however enough people rely on this feature for me to include it.

**Comment by ryantheleach** [comment]
After starting work on implementing this, I quickly found a number of ambiguous / unanswered questions.

https://docs.google.com/document/d/1nIpwQ_XmTWlBRKiKtG_3QxwDDJtAeVP3AjzlnCR0GJY/edit?usp=sharing

**Comment by astei** [comment]
With #247 we have made the decision to simply adopt the BungeeCord plugin messaging API for Velocity 1.1.0. This causes the fewest disruptions and ensures maximum compatibility.
