### ISSUE TITLE
Client disconnected with cast error when moving servers.

### ISSUE THREAD

**Issue by PurpleIsEverything** [VelocityPowered/Velocity#69]
@dualspiral Asked for this to be posted here.

https://paste.ubuntu.com/p/rG25CTbz6J/

This error occurs when moving between a SpongeVanilla lobby and a Direwolf20 1.12 server on its latest recommended release. Player information forwarding is enabled and the DW server is running SpongeForge.

**Comment by dualspiral** [comment]
Yep, I can confirm this, but to get it to run, you need to go from lobby -> modded -> lobby -> modded (last one breaks).

Looks like we're sending a reset packet when it's not needed, that is, when we're on vanilla and in a reset state already.

**Comment by PurpleIsEverything** [comment]
Unfortunately this issue showed itself again this morning, this time with a direct connection to a FTB Revelation server with no lobby connection inbetween. https://paste.ubuntu.com/p/zj8Vfj8xxX/

**Comment by astei** [comment]
Going to ask @dualspiral to look into this, I am on a time crunch myself.
