### ISSUE TITLE
Error setting tablist header and footer during LoginEvent.

### ISSUE THREAD

**Issue by PurpleIsEverything** [VelocityPowered/Velocity#71]
https://paste.ubuntu.com/p/JsBbtF8JP5/

**Comment by astei** [comment]
`LoginEvent` fires too early in the login process to send the tab list packets. At that point, the connection still remains in the login state. Obviously, you can't send tablist packets while you're still in the login state!

I think the proper fix is a better error message along with a `PostLoginEvent` that fires after the `ServerLoginSuccess` packet is sent (indicating we've now switched to the play state, where you can send these packets).

This is not a bug, but a missing feature to add.
