### ISSUE TITLE
bug - nullpointerexception

### ISSUE THREAD

**Issue by BukkitTNT** [VelocityPowered/Velocity#87]
Stacktrace: https://hastebin.com/rowehiluwu.bash

Mode: Legacy (1.8)
Serversoftware: Paperspigot 

Occurred randomly while switching the server

**Comment by astei** [comment]
Please post your stacktrace on a different pastebin other than hastebin because it doesn't work for me. Try [Gist](https://gist.github.com).

**Comment by BukkitTNT** [comment]
https://gist.github.com/BukkitTNT/a0f4ab4f6b78cd66a23945c0da702684
