### ISSUE TITLE
new lines are white

### ISSUE THREAD

**Issue by BukkitTNT** [VelocityPowered/Velocity#91]
When sending messages to the player the message is after line-breaks white

**Comment by DoNotSpamPls** [comment]
He's probably talking about the automatic line breaks when the message gets longer than 1 line. I fixed that by using the legacy ComponentSerializer (or whatever that is called). But yeah, it's a bit of an issue.

**Comment by Leymooo** [comment]
try use
ComponentSerializers.LEGACY.deserialize(message, '&');

**Comment by astei** [comment]
This isn't an issue in Velocity, AFAIK. If there is a bug, it is in [KyoriPowered/text](https://github.com/kyoripowered/text).

**Comment by lucko** [comment]
@BukkitTNT Can you show the code you're using to send the message?

**Comment by DoNotSpamPls** [comment]
@lucko while I'm not mr. BukkitTNT, with [this code](https://gist.github.com/DoNotSpamPls/704e41be0b36f85365d01c7058645d0f) you can see the bug for yourself, this is the result:

![](https://ranked.is-la.me/c1706a.png)

**Comment by lucko** [comment]
Your code doesn't compile.

Line 35:

```java
@NonNull String message = ComponentSerializers.LEGACY.deserialize(builder.substring( 0, builder.length() - 1 ));
```

is not valid.

The deserialize method does not return a string.

![](https://luck.sh/SXfJcGsTI4sMD5i-M6NwQOQuu_E=)

**Comment by lucko** [comment]
`LegacyChatColorUtils` shouldn't really be in the Velocity API. It has no valid use in plugins.

The correct version of the code you gave is as follows.

https://gist.github.com/lucko/cbef3c9e383201163371f68d6f4ea244

**Comment by astei** [comment]
@lucko I really do agree with you here, but I'm loathe to make any more breaking API changes.

**Comment by lucko** [comment]
Better to make breakages now as opposed to later.

I'd argue that any current usages of that method are by mistake - you're doing plugin authors a favour by removing it.

**Comment by DoNotSpamPls** [comment]
@lucko whoops, I meant to remove the ComponentSerializers part entirely, and just leave the LegacyChatCOlorUtils above.

**Comment by lucko** [comment]
You shouldn't be using LegacyChatColorUtils. I've posted the correct usage above.

**Comment by PurpleIsEverything** [comment]
I personally very rarely hard-core chat messages so I do make use of the & color code deserialization.

**Comment by DoNotSpamPls** [comment]
@PurpleIsEverything lucko has a point though, there is zero need to use the LegacyChatColorUtils, because the legacy deserializer from Kyori/text can already handle that 😃

**Comment by astei** [comment]
`ComponentSerializers.LEGACY` does what most people need with components, especially since it takes in a custom format code. I will open a PR to remove the `translate` method.

I am keeping `LegacyChatColorUtils#removeFormatting()` for efficiency and conciseness's sake: `ComponentSerializers.PLAIN.serialize(ComponentSerializers.LEGACY.deserialize(""))` isn't particularly concise and does more work than it needs to.

**Comment by lucko** [comment]
@PurpleIsEverything That's fine - I often store messages like that too. However, the color coded messages need to be deserialized using the appropriate method on the `ComponentSerializers.LEGACY` instance, **not** using `LegacyChatColorUtils`.

@astei No reason why plugin authors should be performing any sort of legacy text manipulation - the Velocity API accepts `Component`s in all places. Soooo I still stand by my opinion that the class has no place being in the API at all 😄

**Comment by PurpleIsEverything** [comment]
Sounds good to me too.

**Comment by DoNotSpamPls** [comment]
@lucko as a plugin author, I use the legacy deserializer to parse messages from the config that use the `&` color code, since having JSON monstrosities in the config isn't really very user-friendly. I'd much rather give them the option to just type "&e&lHello world!" and me parsing it from there 😛

**Comment by astei** [comment]
@DoNotSpamPls `ComponentSerializers.LEGACY.deserialize(String, char)` does what you need, just pass in `'&'`.

**Comment by DoNotSpamPls** [comment]
Yes, I'm using that, I'm just talking about lucko's opinion that `no reason why plugin authors should be performing any sort of legacy text manipulation`

**Comment by astei** [comment]
By that, he means that in general, you should be working in the JSON world, and only use legacy text in limited situations (backwards compatibility, reading from configuration, ...)
